-- Deprecated: schema is managed via Supabase migrations.
--
-- Source of truth: supabase/migrations/
-- Baseline: supabase/migrations/20260630120000_baseline_schema.sql
--
-- To apply schema changes:
--   pnpm run db:new <description>   # create a new migration file
--   pnpm run db:migrate           # push pending migrations to production
--
-- See supabase/README.md for the full workflow.
